# Generated by Django 3.1.1 on 2020-12-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_post_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
