# Generated by Django 3.1.1 on 2021-01-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210107_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the button below to view the entire Post', max_length=255),
        ),
    ]
